export interface Game {
  id: string;
  titleMarathi: string;
  titleEnglish: string;
  description: string;
  emoji: string;
  color: string;
  category: string;
  path: string;
  status: 'available' | 'coming-soon';
}

export const games: Game[] = [
  {
    id: 'spend-money',
    titleMarathi: 'बिल गेट्सचे पैसे खर्च करा',
    titleEnglish: 'Spend Bill Gates\' Money',
    description: 'खरेदी करा, विक्रय करा, आणि अरबपती व्हा',
    emoji: '💰',
    color: 'from-cyan-500 to-blue-600',
    category: 'spending',
    path: '/spend-money',
    status: 'available',
  },
  {
    id: 'clicker',
    titleMarathi: 'महाराष्ट्र उद्योग',
    titleEnglish: 'Maharashtra Industries',
    description: 'क्लिक करा आणि महाराष्ट्राचा व्यावसायिक साम्राज्य बनवा',
    emoji: '🏭',
    color: 'from-orange-500 to-red-600',
    category: 'clicker',
    path: '/clicker',
    status: 'available',
  },
  {
    id: 'mandala',
    titleMarathi: 'मंडळ रंग',
    titleEnglish: 'Mandala Art',
    description: 'सुंदर मंडळ तयार करा आणि अंक मिळवा',
    emoji: '🎨',
    color: 'from-purple-500 to-pink-600',
    category: 'creative',
    path: '/mandala',
    status: 'available',
  },
  {
    id: 'counter',
    titleMarathi: 'दिवसांची गणना',
    titleEnglish: 'Days Counter',
    description: 'महत्वाचे दिवस मोजा आणि स्मृती साठवा',
    emoji: '📅',
    color: 'from-green-500 to-emerald-600',
    category: 'utility',
    path: '/counter',
    status: 'available',
  },
  {
    id: 'craft',
    titleMarathi: 'मराठी रचना',
    titleEnglish: 'Marathi Creation',
    description: 'मराठी संकल्पना एकत्र करा आणि नवीन गोष्टी तयार करा',
    emoji: '✨',
    color: 'from-yellow-500 to-orange-600',
    category: 'creative',
    path: '/craft',
    status: 'available',
  },
  {
    id: 'dilemma',
    titleMarathi: 'नैतिक दुविधा',
    titleEnglish: 'Ethical Dilemmas',
    description: 'मराठी सांस्कृतिक परिस्थितींमधील निर्णय घ्या',
    emoji: '⚖️',
    color: 'from-amber-500 to-orange-600',
    category: 'thinking',
    path: '/dilemma',
    status: 'available',
  },
  {
    id: 'size-compare',
    titleMarathi: 'आकार तुलना',
    titleEnglish: 'Size Comparison',
    description: 'विविध वस्तूंचे आकार तुलना करा',
    emoji: '📏',
    color: 'from-teal-500 to-cyan-600',
    category: 'education',
    path: '/size-compare',
    status: 'available',
  },
  {
    id: 'tourism',
    titleMarathi: 'महाराष्ट्र दर्शन',
    titleEnglish: 'Maharashtra Tourism',
    description: 'मराठी स्मारकांचा आभासी दौरा करा',
    emoji: '🏛️',
    color: 'from-amber-500 to-orange-600',
    category: 'education',
    path: '/monument-tour',
    status: 'available',
  },
  {
    id: 'escalating-quiz',
    titleMarathi: 'वाढणारी क्विझ',
    titleEnglish: 'Escalating Quiz',
    description: 'सतत कठिण होणार्या सह वाढणारी क्विझ स्वीकारा',
    emoji: '🚀',
    color: 'from-indigo-500 to-purple-600',
    category: 'quiz',
    path: '/escalating-quiz',
    status: 'available',
  },
  {
    id: 'rock-paper-scissors',
    titleMarathi: 'रॉक पेपर कात्री',
    titleEnglish: 'Rock Paper Scissors',
    description: 'संगणकाविरुद्ध खेळा',
    emoji: '👊',
    color: 'from-orange-500 to-red-600',
    category: 'clicker',
    path: '/rock-paper-scissors',
    status: 'available',
  },
  {
    id: 'color-matcher',
    titleMarathi: 'रंग जुळवणे',
    titleEnglish: 'Color Matcher',
    description: 'रंग संगणालाला सुलवून करा आणि अंक अर्जन करा',
    emoji: '🌈',
    color: 'from-pink-500 to-rose-600',
    category: 'creative',
    path: '/color-matcher',
    status: 'available',
  },
  {
    id: 'reaction-time',
    titleMarathi: 'प्रतिक्रिया वेळ तसणी',
    titleEnglish: 'Reaction Time Tester',
    description: 'तुमची प्रतिक्रिया वेळ कीती तसणी घेता',
    emoji: '⚡',
    color: 'from-red-500 to-pink-600',
    category: 'thinking',
    path: '/reaction-time',
    status: 'available',
  },
  {
    id: 'useless-clicker',
    titleMarathi: 'निरुपयोगी क्लिकर',
    titleEnglish: 'Useless Clicker',
    description: 'कुणाची मदत न करता केवळ संख्या बधवा',
    emoji: '🖱️',
    color: 'from-cyan-500 to-blue-600',
    category: 'clicker',
    path: '/useless-clicker',
    status: 'available',
  },
  {
    id: 'perfect-shape',
    titleMarathi: 'परिपूर्ण वर्तुळ काढा',
    titleEnglish: 'Perfect Shape Drawer',
    description: 'परिपूर्ण वर्तुळ काढा आणि अंक मिळवा',
    emoji: '⭕',
    color: 'from-green-500 to-emerald-600',
    category: 'creative',
    path: '/perfect-shape',
    status: 'available',
  },
  {
    id: 'memory-doodle',
    titleMarathi: 'स्मृती डूडल',
    titleEnglish: 'Memory Doodle',
    description: 'रंगांचा क्रम लक्षात ठेवा आणि पुनरावृत्ती करा',
    emoji: '🎮',
    color: 'from-red-500 to-pink-600',
    category: 'thinking',
    path: '/memory-doodle',
    status: 'available',
  },
  {
    id: 'infinite-mixer',
    titleMarathi: 'अनंत मिक्सर',
    titleEnglish: 'Infinite Mixer',
    description: 'वस्तू एकत्र करा आणि नवीन गोष्टी तयार करा',
    emoji: '🧪',
    color: 'from-purple-500 to-indigo-600',
    category: 'creative',
    path: '/infinite-mixer',
    status: 'available',
  },
  {
    id: 'lagori',
    titleMarathi: 'लागोरी',
    titleEnglish: 'Lagori Game',
    description: 'मराठी पारंपरिक खेळ - सर्व स्टॅक खाली करा',
    emoji: '📦',
    color: 'from-orange-500 to-yellow-600',
    category: 'education',
    path: '/lagori',
    status: 'available',
  },
  {
    id: 'diwali',
    titleMarathi: 'दिवाळी उत्सव',
    titleEnglish: 'Diwali Celebration',
    description: 'आकाशात फटाके फोडा आणि प्रकाश फैलवा',
    emoji: '🪔',
    color: 'from-yellow-500 to-orange-600',
    category: 'education',
    path: '/diwali',
    status: 'available',
  },
  {
    id: 'holi',
    titleMarathi: 'होळी - रंगांचा सण',
    titleEnglish: 'Holi Colors',
    description: 'रंग फेकून होळीचा सण साजरा करा',
    emoji: '🎨',
    color: 'from-pink-500 to-rose-600',
    category: 'education',
    path: '/holi',
    status: 'available',
  },
  {
    id: 'cultural-quiz',
    titleMarathi: 'महाराष्ट्रीयन संस्कृती क्विझ',
    titleEnglish: 'Cultural Quiz',
    description: 'महाराष्ट्रीयन संस्कृती आणि इतिहास बद्दल प्रश्न',
    emoji: '🏛️',
    color: 'from-purple-500 to-indigo-600',
    category: 'quiz',
    path: '/cultural-quiz',
    status: 'available',
  },
    {
    id: 'budget-catcher',
    titleMarathi: 'बजेट कॅचर',
    titleEnglish: 'Budget Catcher',
    description: 'पडणारे बजेट पकडा आणि उच्च स्कोअर मिळवा',
    emoji: '💰',
    color: 'from-green-500 to-emerald-600',
    category: 'clicker',
    path: '/budget-catcher',
    status: 'available',
  },
  {
          id: 'nokia-snake',
    titleMarathi: 'नोकिया स्नेक',
    titleEnglish: 'Nokia Snake',
    description: 'क्लासिक नोकिया स्नेक गेम खेळा',
    emoji: '🐍',
    color: 'from-green-500 to-teal-600',
    category: 'arcade',
    path: '/nokia-snake',
    status: 'available',
  },
    {
    id: 'design',
    titleMarathi: 'भारतीय स्मार्टफोन डिजाइन',
    titleEnglish: 'Indian Phone Design',
    description: 'भारतीय बाजारासाठी स्मार्टफोन डिजाइन करा',
    emoji: '📱',
    color: 'from-blue-500 to-cyan-600',
    category: 'design',
    path: '/design',
    status: 'coming-soon',
  },
  {
    id: 'music',
    titleMarathi: 'मराठी संगीत रचना',
    titleEnglish: 'Marathi Music Creator',
    description: 'परंपरागत आणि आधुनिक संगीत मिश्रित करा',
    emoji: '🎵',
    color: 'from-red-500 to-pink-600',
    category: 'creative',
    path: '/music',
    status: 'coming-soon',
  },
    {
    id: 'simon-memory',
    titleMarathi: 'सायमन मेमरी गेम',
    titleEnglish: 'Simon Memory Game',
    description: 'रंगांचा क्रम लक्षात ठेवा आणि पुन्हा करा',
    emoji: '🎮',
    color: 'from-purple-500 to-pink-600',
    category: 'clicker',
    path: '/simon-memory',
    status: 'available',
  },
  {
    id: 'teddy-platformer',
    titleMarathi: 'टेडी प्लॅटफॉर्मर',
    titleEnglish: 'Teddy Platformer',
    description: 'टेडी बेअरसोबत प्लॅटफॉर्म गेम खेळा',
    emoji: '🧸',
    color: 'from-yellow-500 to-orange-600',
    category: 'clicker',
    path: '/teddy-platformer',
    status: 'available',
  },
];

export const categories = [
  { id: 'all', name: 'सर्व खेळ', nameEn: 'All Games' },
  { id: 'spending', name: 'खर्च करा', nameEn: 'Spending' },
  { id: 'clicker', name: 'क्लिकर', nameEn: 'Clicker' },
  { id: 'creative', name: 'रचनात्मक', nameEn: 'Creative' },
  { id: 'quiz', name: 'प्रश्नमंजुषा', nameEn: 'Quiz' },
  { id: 'utility', name: 'उपयोगिता', nameEn: 'Utility' },
  { id: 'design', name: 'डिजाइन', nameEn: 'Design' },
  { id: 'education', name: 'शिक्षा', nameEn: 'Education' },
  { id: 'thinking', name: 'विचार', nameEn: 'Thinking' }
];
